### ISSUE TITLE
Out of tree builds

### ISSUE THREAD

**Issue by Psirus** [dinau/imguin#13]
How can I install imguin so that I can build my application outside of the imguin tree? All the examples assume they live inside the tree (e.g. `switch "path","../../src" # for "import glad/gl"`). Thank you for the library.

**Comment by dinau** [comment]
Thank you for the comment,  
I will modify that imguin can be built   
outside of the tree.

**Comment by dinau** [comment]
Updated.
It should be able to install as nimble package,

```sh
nimble install https://github.com/dinau/imguin
```

**Comment by Psirus** [comment]
Thanks, that works.
