### ISSUE TITLE
ImNodes example not running

### ISSUE THREAD

**Issue by system64MC** [dinau/imguin#16]
Hi. I tried the example projects and it looks like I can't run the ImNodes example.

Here is what it says :
```
Added: /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc
free(): double free detected in tcache 2
SIGABRT: Abnormal termination.
Abandon (core dumped)
```
It looks like it happens while calling NodeEditorInitialize().
I'm on POP!_OS 2204 LTS and I use Nim 2.2.0.

Is this normal?
Thanks for your answer!

**Comment by dinau** [comment]
Thank you for this report.
I can reproduce this problem on my Linux Mint 22.
I will look over this issue.

**Comment by dinau** [comment]
Updated soruces.  
First delete  old `save_load.bytes` file and run program.

**Comment by system64MC** [comment]
> Updated sources. First delete old `save_load.bytes` file and `make run`.

It works! Thanks!

Is it also possible to make a project without Make (Nim tools only)? I tried to make a baremetal ImGUI test with ImNodes, I have linker errors.

**Comment by dinau** [comment]
I will add this to README file,

```sh
pwd
examples/glfw_opnegl3_imnodes

nim c -d:release -d:strip -d:ImNodesEnable glfw_opengl3_imnodes.nim
```

**Comment by system64MC** [comment]
> I will add this to README file,
> 
> ```sh
> pwd
> examples/glfw_opnegl3_imnodes
> 
> nim c -d:release -d:strip -d:ImNodesEnable glfw_opengl3_imnodes.nim
> ```

That was quite straightforward! Thanks!
However I noticed a problem while trying to cross-compile from Linux to Windows. I have this error :
```
system64@pop-os:~/programmation/testNimImNodes/glfw_opengl3$ nim compile --os:windows glfw_opengl3.nim 

#### [ gcc ] Compiler ####

Hint: used config file '/home/system64/.choosenim/toolchains/nim-2.2.0/config/nim.cfg' [Conf]
Hint: used config file '/home/system64/.choosenim/toolchains/nim-2.2.0/config/config.nims' [Conf]
Hint: used config file '/home/system64/programmation/testNimImNodes/glfw_opengl3/config.nims' [Conf]
............................................................................................................................
/home/system64/.nimble/pkgs2/imguin-1.91.4.0-d2351593496ca43b2f019cdaba21a66f5b7e0bed/imguin/cimgui.nim(79, 12) Error: cannot find: \home\system64\.nimble\pkgs2\imguin-1.91.4.0-d2351593496ca43b2f019cdaba21a66f5b7e0bed\imguin\private\cimgui\cimgui.cpp
```

Seems it messes up with the "/".

**Comment by dinau** [comment]
Hi,
I have not tried to cross compilation for Windows OS on Linux OS.  
Would you try this ?
[Cross compilation to Windows, linker error (unrecognized option '-z'](https://forum.nim-lang.org/t/11302#73838)

https://nim-lang.org/docs/nimc.html#crossminuscompilation-for-windows

I'll try this later.

**Comment by system64MC** [comment]
> Hi, I have not tried to cross compilation for Windows OS on Linux OS. Would you try this ? [Cross compilation to Windows, linker error (unrecognized option '-z'](https://forum.nim-lang.org/t/11302#73838)
> 
> https://nim-lang.org/docs/nimc.html#crossminuscompilation-for-windows
> 
> I'll try this later.

It still doesn't work sadly.

**Comment by system64MC** [comment]
> nim compile --os:windows glfw_opengl3.nim



> > Hi, I have not tried to cross compilation for Windows OS on Linux OS. Would you try this ? [Cross compilation to Windows, linker error (unrecognized option '-z'](https://forum.nim-lang.org/t/11302#73838)
> > https://nim-lang.org/docs/nimc.html#crossminuscompilation-for-windows
> > I'll try this later.
> 
> It still doesn't work sadly.

Some progress!
I noticed that if I add ".replace("\\", "/")" after each joinPath statement, it solve the errors. A way to solve this might be to create a function that changes the path only if we compile from a Linux to Windows
like joinPath(ImguiRootPath,"backends","imgui_impl_glfw.cpp").replaceIfWeAreOnLinux("\\", "/")

However I also have another error : /home/system64/.nimble/pkgs2/imguin-1.91.4.0-d2351593496ca43b2f019cdaba21a66f5b7e0bed/imguin/private/cimgui/imgui/backends/imgui_impl_glfw.cpp:102:10: fatal error: GLFW/glfw3.h
Which means it can't find GLFW/glfw3.h (however everything works fine when I compile from Linux to Linux).

**Comment by dinau** [comment]
I can successfully generated Windows exe file using your idea and it works well on Windows OS.

> it can't find GLFW/glfw3.h (however everything works fine when I compile from Linux to Linux).

This error can silent by changing `cimgui.nim` line 56,

from 

```nim
{.passC:"-I" & joinPath(staticExec("nimble path nimgl").strip,"nimgl","private","glfw","include").}
```

to 

```nim
{.passC:"-I" & joinPath(staticExec("nimble path nimgl").strip,"nimgl","private","glfw","include").replace("\\", "/").}
```

I've executed this command,

```sh
nim c -d:release -d:strip -d:mingw --passL:-lstdc++ glfw_opengl3.nim 
```

**Comment by system64MC** [comment]
> ```shell
> nim c -d:release -d:strip -d:mingw --passL:-lstdc++ glfw_opengl3.nim 
> ```

It works! It also works with --os;windows!
I think we have found and solved the issue!

**Comment by dinau** [comment]
Thank you your interesting idea.

**Comment by system64MC** [comment]
> Thank you for your interesting idea.

You are welcome! Do you want me to try to do a pull request with the changes I suggested?

**Comment by dinau** [comment]
I would appreciate your PR.

**Comment by system64MC** [comment]
> I would appreciate your PR.

Already! I will do this once I'm back home.

I also try to add ImGui-knobs, an addon for Dear ImGui that adds... Knobs.
I achieved to make a C interface, however should I add the Nim procs manually or is there something to do to generate them automatically?

**Comment by dinau** [comment]
I think you should make for instance `cimknobs` repository that has `imgui-knobs` project as submodule.

```sh
`-- cimknobs
    |-- cimknobs.h
    |-- examples
    |   `-- main.c
    |   `-- Makefile or CMakeLists.txt
    `-- imgui-knobs
        `__ ...
        `__ ...
```

I will fetch your `cimknobs` project to Imguin project same as cimgui/cimplot/... etc.  
and I wiil add to cimgui.nim,

```nim
  when defined(ImKnobsEnable):
    {.passC:"-I" & CImKnobRootPath.}
    ...snip...
```

Nim header file of `cimknobs` will be auto generate by futhark and included `cimgui.nim`.

Build command may be

```sh
pwd 
imguin/examples/imknobs_opengl3
nim c -d:ImKnobsEnable imknobs_opengl3.nim
```

**Comment by system64MC** [comment]
> I think you should make for instance `cimknobs` repository that has `imgui-knobs` project as submodule.
> 
> ```shell
> `-- cimknobs
>     |-- cimknobs.h
>     |-- examples
>     |   `-- main.c
>     |   `-- Makefile or CMakeLists.txt
>     `-- imgui-knobs
>         `__ ...
>         `__ ...
> ```
> 
> I will fetch your `cimknobs` project to Imguin project same as cimgui/cimplot/... etc. and I wiil add to cimgui.nim,
> 
> ```nim
>   when defined(ImKnobsEnable):
>     {.passC:"-I" & CImKnobRootPath.}
>     ...snip...
> ```
> 
> Nim header file of `cimknobs` will be auto generated by futhark and included in`cimgui.nim`.
> 
> Build command may be
> 
> ```shell
> pwd 
> imguin/examples/imknobs_opengl3
> nim c -d:ImKnobsEnable imknobs_opengl3.nim
> ```

I added cimgui knobs into my Imguin fork like what you did for the others ImGUI extensions. Is that OK?
I also sent a pull request.

**Comment by dinau** [comment]
Thank you PR. 
I'll check that and merge within a few days.

**Comment by dinau** [comment]
Done.

**Comment by system64MC** [comment]
> Done.

Thanks! I will have a look!

Do you also know how I can statically link the glibc / glibc++ or how I can use musl please? I'm concerned about compatibility with older Linux distros.

**Comment by dinau** [comment]
I'm not familiar with static link on Linux,
but I know it generally is very difficult on Linux :-)  
- First  
Whether can this example be compiled or not on Linux with static link,  
[cimgui:example_glfw_opengl3](https://github.com/cimgui/cimgui/tree/docking_inter/backend_test/example_glfw_opengl3)
- Second   
If an application uses the nimble libraries, at least the libraires have to be appropriately compiled with static link option on Linux.
